language: android
os: linux
dist: trusty

android:
  components:
    - build-tools-29.0.2
    - android-29
    - extra

script: ./gradlew build

deploy:
  provider: script
  script: ./gradlew assembleRelease appDistributionUploadRelease
  on:
    branch: master
