language: android
os: linux
dist: trusty

android:
  components:
    - build-tools-29.0.2
    - android-29
    - extra

before_install: |
  openssl aes-256-cbc \
  -K $encrypted_8b3bd3f612ae_key \
  -iv $encrypted_8b3bd3f612ae_iv \
  -in sec/miocheck-google-creds.json.enc \
  -out sec/miocheck-google-creds.json -d

script: ./gradlew build

deploy:
  provider: script
  skip_cleanup: true
  script: export GOOGLE_APPLICATION_CREDENTIALS="$PWD/sec/miocheck-google-creds.json" && ./gradlew assembleRelease appDistributionUploadRelease
  cleanup: false
  on:
    branch: master
